services:
  keycloak:
    build: .
    container_name: green-sky-keycloak
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    volumes:
      - ./theme/green-sky-login:/opt/keycloak/themes/green-sky-login
      - ./realm:/opt/keycloak/data/import
    command:
      - start-dev
      - --import-realm
    ports:
      - "8080:8080"
